"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let x;
x = "farhan";
x = 14;
x = {};
x = [];
x = false;
x = undefined;
let y;
y = "farhan";
y = 14;
y = {};
y = [];
y = false;
y = undefined;
let var1;
let var2 = var1;
let var3 = var1;
// let var4 : string = var1;
// let var5 : Number = var1;
// let var6 : boolean = var1;
